### ISSUE TITLE
프로젝트 구조 참고

### ISSUE THREAD

**Issue by mrchypark** [codingpot/lookup-stock#4]
https://github.com/pojntfx/liwasc

**Comment by kkweon** [comment]
* 바이너리(*.wasm) 제거 / 용량 매우 큼
* 바이너리 제거는 단순 제거 후 커밋이 아니라 전체 히스토리에서 완전히 제거되도록 필터브랜치 및 포스 푸시 사용 해야 함. 안그러면 용량은 계속 늘어남.
* docs/ 대신에 gh-branch 브랜치 사용
* gh-branch 에는 소스가 아니라 index.html 만 들어가도록 변경
* 빌드 아웃풋이 체크인 되면 안됨

**Comment by kkweon** [comment]
레퍼런스 workflow 

https://github.com/codingpot/pr12er/blob/main/.github/workflows/ci.yml#L103-L128

Flutter지만 Go 로 변경하면 동일함

핵심 로직

`client/build/web` 에 있는 걸 gh-pages 브랜치로 전부 옮겨라

```yaml
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ./client/build/web
```
